runtime: java11 # or another supported version
service: api

instance_class: F2

env_variables:
  BUCKET_NAME: "flickr-gcs-bucket"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /api/.*
  secure: always
  redirect_http_response_code: 301
  script: auto